using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HiNativeShared.Services
{
    public class DecodeService
    {
        public static string DecodeLanguage(int languageID)
        {
            switch (languageID)
            {
                case 1: return "Afrikaans";
                case 2: return "Albanian";
                case 3: return "Arabic";
                case 4: return "Azerbaijani";
                case 5: return "Ainu";
                case 6: return "Armenian";
                case 7: return "Aymara";
                case 8: return "Azeri";
                case 9: return "Basque";
                case 10: return "Belarusian";
                case 11: return "Bengali";
                case 12: return "Bosnian";
                case 13: return "Bulgarian";
                case 14: return "Catalan";
                case 15: return "Cherokee";
                case 16: return "Croatian";
                case 17: return "Czech";
                case 18: return "Danish";
                case 19: return "Dutch";
                case 20: return "Dutch (Belgium)";
                case 21: return "English (UK)";
                case 22: return "English (US)";
                case 23: return "Esperanto";
                case 24: return "Estonian";
                case 25: return "Faroese";
                case 26: return "Finnish";
                case 27: return "French (Canada)";
                case 28: return "French (France)";
                case 29: return "Frisian";
                case 30: return "Galician";
                case 31: return "Georgian";
                case 32: return "German";
                case 33: return "Greek";
                case 34: return "Guarani";
                case 35: return "Gujarati";
                case 36: return "Haitian Creole";
                case 37: return "Hawaiian";
                case 38: return "Hebrew";
                case 39: return "Hindi";
                case 40: return "Hungarian";
                case 41: return "Icelandic";
                case 42: return "Indonesian";
                case 43: return "Irish";
                case 44: return "Italian";
                case 45: return "Japanese";
                case 46: return "Javanese";
                case 47: return "Kannada";
                case 48: return "Kazakh";
                case 49: return "Khmer";
                case 50: return "Klingon";
                case 51: return "Korean";
                case 52: return "Kurdish";
                case 53: return "Laotian";
                case 54: return "Latin";
                case 55: return "Latvian";
                case 56: return "Limburgish";
                case 57: return "Lithuanian";
                case 58: return "Macedonian";
                case 59: return "Malagasy";
                case 60: return "Malay";
                case 61: return "Malayalam";
                case 62: return "Malay";
                case 63: return "Maltese";
                case 64: return "Marathi";
                case 65: return "Mongolian";
                case 66: return "Nepali";
                case 67: return "Northern Sami";
                case 68: return "Norwegian (Bokmål)";
                case 69: return "Norwegian (Nynorsk)";
                case 70: return "Pashto";
                case 71: return "Persian";
                case 72: return "Polish";
                case 73: return "Portuguese (Brazil)";
                case 74: return "Portuguese (Portugal)";
                case 75: return "Punjabi";
                case 76: return "Quechua";
                case 77: return "Romanian";
                case 78: return "Romansh";
                case 79: return "Russian";
                case 80: return "Sanskrit";
                case 81: return "Serbian";
                case 82: return "Simplified Chinese (China)";
                case 83: return "Slavic";
                case 84: return "Slovak";
                case 85: return "Slovenian";
                case 86: return "Somali";
                case 87: return "Spanish (Chile)";
                case 88: return "Spanish (Colombia)";
                case 89: return "Spanish (Mexico)";
                case 90: return "Spanish (Spain)";
                case 91: return "Spanish (Venezuela)";
                case 92: return "Kiswahili";
                case 93: return "Swedish";
                case 94: return "Syriac";
                case 95: return "Tagalog";
                case 96: return "Tajik";
                case 97: return "Tamil";
                case 98: return "Tatar";
                case 99: return "Telugu";
                case 100: return "Thai";
                case 101: return "Tibet";
                case 102: return "Traditional Chinese (Hong Kong)";
                case 103: return "Traditional Chinese (Taiwan)";
                case 104: return "Tongan";
                case 105: return "Turkish";
                case 106: return "Ukrainian";
                case 107: return "Urdu";
                case 108: return "Uzbek";
                case 109: return "Vietnamese";
                case 110: return "Welsh";
                case 111: return "Xhosa";
                case 112: return "Yiddish";
                case 113: return "Zulu";
                default: return "ERROR";
            }
        }

        public static string DecodeCountry(int countryID)
        {
            switch (countryID)
            {
                case 1: return "Afghanistan";
                case 2: return "Åland Islands";
                case 3: return "Albania";
                case 4: return "Algeria";
                case 5: return "American Samoa";
                case 6: return "Andorra";
                case 7: return "Angola";
                case 8: return "Anguilla";
                case 9: return "Antarctica";
                case 10: return "Antigua And Barbuda";
                case 11: return "Argentina";
                case 12: return "Armenia";
                case 13: return "Aruba";
                case 14: return "Australia";
                case 15: return "Austria";
                case 16: return "Azerbaijan";
                case 17: return "Bahamas";
                case 18: return "Bahrain";
                case 19: return "Bangladesh";
                case 20: return "Barbados";
                case 21: return "Belarus";
                case 22: return "Belgium";
                case 23: return "Belize";
                case 24: return "Benin";
                case 25: return "Bermuda";
                case 26: return "Bhutan";
                case 27: return "Bolivia, Plurinational State Of";
                case 28: return "Bonaire, Sint Eustatius And Saba";
                case 29: return "Bosnia And Herzegovina";
                case 30: return "Botswana";
                case 31: return "Bouvet Island";
                case 32: return "Brazil";
                case 33: return "British Indian Ocean Territory";
                case 34: return "Brunei Darussalam";
                case 35: return "Bulgaria";
                case 36: return "Burkina Faso";
                case 37: return "Burundi";
                case 38: return "Cambodia";
                case 39: return "Cameroon";
                case 40: return "Canada";
                case 41: return "Cape Verde";
                case 42: return "Cayman Islands";
                case 43: return "Central African Republic";
                case 44: return "Chad";
                case 45: return "Chile";
                case 46: return "China";
                case 47: return "Christmas Island";
                case 48: return "Cocos (keeling) islands";
                case 49: return "Colombia";
                case 50: return "Comoros";
                case 51: return "Congo";
                case 52: return "Congo, The Democratic Republic Of The";
                case 53: return "Cook Islands";
                case 54: return "Costa Rica";
                case 56: return "Croatia";
                case 57: return "Cuba";
                case 58: return "Curaçao";
                case 59: return "Cyprus";
                case 60: return "Czech Republic";
                case 55: return "Côte D'ivoire";
                case 61: return "Denmark";
                case 62: return "Djibouti";
                case 63: return "Dominica";
                case 64: return "Dominican Republic";
                case 65: return "Ecuador";
                case 66: return "Egypt";
                case 67: return "El Salvador";
                case 68: return "Equatorial Guinea";
                case 69: return "Eritrea";
                case 70: return "Estonia";
                case 71: return "Ethiopia";
                case 72: return "Falkland Islands (malvinas)";
                case 73: return "Faroe Islands";
                case 74: return "Fiji";
                case 75: return "Finland";
                case 76: return "France";
                case 77: return "French Guiana";
                case 78: return "French Polynesia";
                case 79: return "French Southern Territories";
                case 80: return "Gabon";
                case 81: return "Gambia";
                case 82: return "Georgia";
                case 83: return "Germany";
                case 84: return "Ghana";
                case 85: return "Gibraltar";
                case 86: return "Greece";
                case 87: return "Greenland";
                case 88: return "Grenada";
                case 89: return "Guadeloupe";
                case 90: return "Guam";
                case 91: return "Guatemala";
                case 92: return "Guinea";
                case 93: return "Guinea-bissau";
                case 94: return "Guyana";
                case 95: return "Haiti";
                case 96: return "Heard Island And Mcdonald Islands";
                case 97: return "Holy See (vatican City State)";
                case 98: return "Honduras";
                case 99: return "Hong Kong";
                case 100: return "Hungary";
                case 101: return "Iceland";
                case 102: return "India";
                case 103: return "Indonesia";
                case 104: return "Iran, Islamic Republic Of";
                case 105: return "Iraq";
                case 106: return "Ireland";
                case 107: return "Isle Of Man";
                case 108: return "Israel";
                case 109: return "Italy";
                case 110: return "Jamaica";
                case 111: return "Japan";
                case 112: return "Jersey";
                case 113: return "Jordan";
                case 114: return "Kazakhstan";
                case 115: return "Kenya";
                case 116: return "Kiribati";
                case 117: return "Korea, Democratic People's Republic Of";
                case 118: return "Korea, Republic Of";
                case 119: return "Kuwait";
                case 120: return "Kyrgyzstan";
                case 121: return "Lao People's Democratic Republic";
                case 122: return "Latvia";
                case 123: return "Lebanon";
                case 124: return "Lesotho";
                case 125: return "Liberia";
                case 126: return "Libya";
                case 127: return "Liechtenstein";
                case 128: return "Lithuania";
                case 129: return "Luxembourg";
                case 130: return "Macao";
                case 131: return "Macedonia, The Former Yugoslav Republic Of";
                case 132: return "Madagascar";
                case 133: return "Malawi";
                case 134: return "Malaysia";
                case 135: return "Maldives";
                case 136: return "Mali";
                case 137: return "Malta";
                case 138: return "Marshall Islands";
                case 139: return "Martinique";
                case 140: return "Mauritania";
                case 141: return "Mauritius";
                case 142: return "Mayotte";
                case 143: return "Mexico";
                case 144: return "Micronesia, Federated States Of";
                case 145: return "Moldova, Republic Of";
                case 146: return "Monaco";
                case 147: return "Mongolia";
                case 148: return "Montenegro";
                case 149: return "Montserrat";
                case 150: return "Morocco";
                case 151: return "Mozambique";
                case 152: return "Myanmar";
                case 153: return "Namibia";
                case 154: return "Nauru";
                case 155: return "Nepal";
                case 156: return "Netherlands";
                case 157: return "New Caledonia";
                case 158: return "New Zealand";
                case 159: return "Nicaragua";
                case 160: return "Niger";
                case 161: return "Nigeria";
                case 162: return "Niue";
                case 163: return "Norfolk Island";
                case 164: return "Northern Mariana Islands";
                case 165: return "Norway";
                case 166: return "Oman";
                case 167: return "Pakistan";
                case 168: return "Palau";
                case 169: return "Palestine, State Of";
                case 170: return "Panama";
                case 171: return "Papua New Guinea";
                case 172: return "Paraguay";
                case 173: return "Peru";
                case 174: return "Philippines";
                case 175: return "Pitcairn";
                case 176: return "Poland";
                case 177: return "Portugal";
                case 178: return "Puerto Rico";
                case 179: return "Qatar";
                case 181: return "Romania";
                case 182: return "Russian Federation";
                case 183: return "Rwanda";
                case 180: return "Réunion";
                case 184: return "Saint Barthélemy";
                case 185: return "Saint Helena, Ascension And Tristan Da Cunha";
                case 186: return "Saint Kitts And Nevis";
                case 187: return "Saint Lucia";
                case 188: return "Saint Martin";
                case 189: return "Saint Pierre And Miquelon";
                case 190: return "Saint Vincent And The Grenadines";
                case 191: return "Samoa";
                case 192: return "San Marino";
                case 193: return "Sao Tome And Principe";
                case 194: return "Saudi Arabia";
                case 195: return "Senegal";
                case 196: return "Serbia";
                case 197: return "Seychelles";
                case 198: return "Sierra Leone";
                case 199: return "Singapore";
                case 200: return "Sint Maarten";
                case 201: return "Slovakia";
                case 202: return "Slovenia";
                case 203: return "Solomon Islands";
                case 204: return "Somalia";
                case 205: return "South Africa";
                case 206: return "South Georgia And The South Sandwich Islands";
                case 207: return "South Sudan";
                case 208: return "Spain";
                case 209: return "Sri Lanka";
                case 210: return "Sudan";
                case 211: return "Suriname";
                case 212: return "Svalbard And Jan Mayen";
                case 213: return "Swaziland";
                case 214: return "Sweden";
                case 215: return "Switzerland";
                case 216: return "Syrian Arab Republic";
                case 217: return "Taiwan";
                case 218: return "Tajikistan";
                case 219: return "Tanzania, United Republic Of";
                case 220: return "Thailand";
                case 221: return "Timor-leste";
                case 222: return "Tokelau";
                case 223: return "Tonga";
                case 224: return "Trinidad And Tobago";
                case 225: return "Tunisia";
                case 226: return "Turkey";
                case 227: return "Turkmenistan";
                case 228: return "Turks And Caicos Islands";
                case 229: return "Tuvalu";
                case 230: return "Uganda";
                case 231: return "Ukraine";
                case 232: return "United Arab Emirates";
                case 233: return "United Kingdom";
                case 234: return "United States";
                case 235: return "United States Minor Outlying Islands";
                case 236: return "Uruguay";
                case 237: return "Uzbekistan";
                case 238: return "Vanuatu";
                case 239: return "Venezuela, Bolivarian Republic Of";
                case 240: return "Vietnam";
                case 241: return "Virgin Islands, British";
                case 242: return "Virgin Islands, U.S.";
                case 243: return "Wallis And Futuna";
                case 244: return "Western Sahara";
                case 245: return "Yemen";
                case 246: return "Zambia";
                case 247: return "Zimbabwe";
                default:
                    return "Error";
            }
        }
    }
}
